name: rsna-knee
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.3.0
  - torchvision=0.18.0
  - pytorch-cuda=12.1
  - numpy=1.26
  - pandas=2.2
  - pillow=10.3
  - pyyaml=6.0
  - tqdm=4.66
  - scikit-learn=1.5
  - scipy=1.13
  - opencv=4.10
  - albumentations=1.4
  - pip=24.0
  - pip:
    - timm==1.0.7
    - wandb==0.17.6
    - kaggle==1.7.4.3
    - python-dotenv==1.0.1